version: "3.7"

services:
  # ---PokeAPI---
  # Starts the PostgreSQL DataBase
  pokedb:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokeapi
    ports:
      - "5432:5432"
    # Starts the PokeAPI
  pokeapi:
    build: pokeapi/
    restart: always
    command: bash -c "python3 app.py"
    volumes:
      - ./pokeapi:/code
    depends_on:
      - pokedb
    environment:
      - database_url=postgres://postgres:postgres@pokedb/pokeapi

  # ---UsersAPI---
  # Starts the PostgreSQL DataBase
  usersdb:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usersapi
    ports:
      - "5433:5433"
  # Starts the UsersAPI
  usersapi:
    build: usersapi/
    restart: always
    command: bash -c "python3 app.py"
    volumes:
      - ./usersapi:/code
    depends_on:
      - usersdb
    environment:
      - database_url=postgres://postgres:postgres@usersdb/usersapi
  
  # ---DigiAPI---
  # Starts the DigiAPI
  digiapi:
    build: digiapi/
    restart: always
    # TODO: this should just call the compiled main
    command: bash -c "go run main.go"
    volumes:
      - ./digiapi:/code
    depends_on:
      - usersdb
    ports:
      - "8000:9000"
    # environment:
    #   - database_url=postgres://postgres:postgres@digidb/digiapi
  
  # ---PGAdmin---
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pokedb
      - usersdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=pokeapi@poke.mon
      - PGADMIN_DEFAULT_PASSWORD=pokemon
    ports:
      - "5050:80"

  # ---Nginx---
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pokeapi
      - usersapi
