version: "3.7"

services:
  # -----PokeAPI-----
  # Starts the PostgreSQL DataBase
  pokedb:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokeapi
    ports:
      - "5432:5432"

  # Starts the PokeAPI
  pokeapi:
    build: pokeapi/
    restart: always
    command: bash -c "python3 app.py"
    volumes:
      - ./pokeapi:/code
    depends_on:
      - pokedb
    environment:
      - api_prefix=/api/v1/pokeapi
      - database_url=postgres://postgres:postgres@pokedb/pokeapi
      - port=8000
      - secret_key=SuperSecretKey # this can be replace using a .env

  # -----UsersAPI-----
  # Starts the PostgreSQL DataBase
  usersdb:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usersapi
    ports:
      - "5433:5433"

  # Starts the UsersAPI
  usersapi:
    build: usersapi/
    restart: always
    command: bash -c "python3 app.py"
    volumes:
      - ./usersapi:/code
    depends_on:
      - usersdb
    environment:
      - api_prefix=/api/v1/users
      - database_url=postgres://postgres:postgres@usersdb/usersapi
      - port=8000
      - secret_key=SuperSecretKey # this can be replace using a .env
  

  # -----DigiAPI-----    
  # Starts the PostgreSQL DataBase
  digidb:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digiapi
    ports:
      - "5434:5434"

  # Starts the DigiAPI
  digiapi:
    build: digiapi/
    restart: always
    # TODO: this should just call the compiled main
    command: bash -c "go run main.go"
    volumes:
      - ./digiapi:/code
    depends_on:
      - digidb
    environment:
      - api_prefix=/api/v1/digiapi
      - database_url=host=digidb user=postgres password=postgres dbname=digiapi
      - port=8000
      - secret_key=SuperSecretKey # this can be replace using a .env
      
  # -----PGAdmin-----
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pokedb
      - usersdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=pokeapi@poke.mon
      - PGADMIN_DEFAULT_PASSWORD=pokemon
    ports:
      - "5050:80"

  # -----Nginx-----
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pokeapi
      - usersapi
