version: "3.7"

services:
  # Starts the PostgreSQL DataBase
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - "5432:5432"
  # Starts the pgadmin
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=pokeapi@poke.mon
      - PGADMIN_DEFAULT_PASSWORD=pokemon
    ports:
      - "5050:80"
  # Starts the PokeAPI
  pokeapi:
    build: pokeapi/
    restart: always
    command: bash -c "python3 app.py"
    volumes:
      - ./pokeapi:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
